switch to serde_yaml_ng :(
serde_yml seems to be AI maintained and runs into an error like this:

Downloading https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/config/crd/bases/jenkins.io_jenkins.yaml
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/libyml-0.0.5/src/scanner.rs:2798:17:
String join would overflow memory bounds
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/e71f9a9a98b0faf423844bf0ba7438f29dc27d58/library/core/src/panicking.rs:76:14
   2: libyml::scanner::yaml_parser_scan_flow_scalar
   3: libyml::scanner::yaml_parser_fetch_flow_scalar
   4: libyml::scanner::yaml_parser_fetch_next_token
   5: libyml::scanner::yaml_parser_fetch_more_tokens
   6: libyml::parser::peek_token
   7: libyml::parser::yaml_parser_parse_block_mapping_value
   8: libyml::parser::yaml_parser_state_machine
   9: libyml::parser::yaml_parser_parse
  10: serde_yml::libyml::parser::Parser::parse_next_event
  11: serde_yml::loader::Loader::next_document
  12: <serde_yml::de::Deserializer as core::iter::traits::iterator::Iterator>::next
  13: <serde_yml::de::Deserializer as core::iter::traits::iterator::Iterator>::next
  14: crd_v1_fetcher::parse_crds
  15: crd_v1_fetcher::main
  16: core::ops::function::FnOnce::call_once

Signed-off-by: Sebastian Hoß <seb@xn--ho-hia.de>